INSERT INTO SEASON VALUES (1, 2017);

INSERT INTO WEEK VALUES (1, 1, 1);
INSERT INTO WEEK VALUES (2, 2, 1);
INSERT INTO WEEK VALUES (3, 3, 1);
INSERT INTO WEEK VALUES (4, 4, 1);
INSERT INTO WEEK VALUES (5, 5, 1);

INSERT INTO TEAM VALUES (1, 'Falcons', 'Atlanta');
INSERT INTO TEAM VALUES (2, 'Bears', 'Chicago');
INSERT INTO TEAM VALUES (3, 'Giants', 'New York');
INSERT INTO TEAM VALUES (4, 'Cowboys', 'Cowboys');

INSERT INTO GAME_PARTICIPANT VALUES (1,1,31);
INSERT INTO GAME_PARTICIPANT VALUES (2,2,28);
INSERT INTO GAME_PARTICIPANT VALUES (3,3,3);
INSERT INTO GAME_PARTICIPANT VALUES (4,4,27);
INSERT INTO GAME_PARTICIPANT VALUES (5,1,10);
INSERT INTO GAME_PARTICIPANT VALUES (6,2,17);
INSERT INTO GAME_PARTICIPANT VALUES (7,3,7);
INSERT INTO GAME_PARTICIPANT VALUES (8,4,45);

INSERT INTO GAME VALUES (1, 1, 2, 1);
INSERT INTO GAME VALUES (2, 3, 4, 1);
INSERT INTO GAME VALUES (3, 5, 8, 2);
INSERT INTO GAME VALUES (4, 6, 7, 2);

